const express=require('express')
const app=express()
require('dotenv').config()
const cors =require('cors')
const tamplateOne =require('./routes')
app.use(cors())
app.use(express.json())
app.use('/',tamplateOne)
app.listen(process.env.PORT,()=>{
    console.log(`Server is running on port ${process.env.PORT}`)
})